app:
  scheduler:
    enable: true
    interval: 5
    force-check-delay: 10s
  githubBaseUrl: https://api.github.com/repos
  stackoverflowBaseUrl: https://api.stackexchange.com/2.3/questions
  botBaseUrl: http://localhost:8090

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
